name: Elixir CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: Vinocis
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setting up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Build image
        uses: docker/build-push-action@v2
        with:
          push: false
          context: .
          target: build
          file: ./Dockerfile
          tags: billet_manager:latest
          cache-from: type=registry,ref=ghcr.io/Vinocis/billet_manager/main-cache:latest
          outputs: type=docker,dest=/tmp/image.tar
          ssh: |
            default=${{ env.SSH_AUTH_SOCK }}
      - name: Upload artifact (app)
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: /tmp/image.tar

      - name: Upload artifact (compose)
        uses: actions/upload-artifact@v2
        with:
          name: compose
          path: docker-compose.yml
  format:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Download artifact (image)
        uses: actions/download-artifact@v2
        with:
          name: app
          path: /tmp
      - name: Download artifact (compose)
        uses: actions/download-artifact@v2
        with:
          name: compose
          path: .
      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Code format
        run: docker run -e MIX_ENV=test --name billet_manager billet_manager:latest mix format --check-formatted

  consistency:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Download artifact (image)
        uses: actions/download-artifact@v2
        with:
          name: app
          path: /tmp
      - name: Download artifact (compose)
        uses: actions/download-artifact@v2
        with:
          name: compose
          path: .
      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Code consistency
        run: docker run -e MIX_ENV=test --name billet_manager billet_manager:latest mix credo --strict

  unit-tests:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Download artifact (image)
        uses: actions/download-artifact@v2
        with:
          name: app
          path: /tmp
      - name: Download artifact (compose)
        uses: actions/download-artifact@v2
        with:
          name: compose
          path: .
      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Starting DB
        run: docker-compose up -d db

      - name: Load Docker image
        run: docker load --input /tmp/image.tar

      - name: Unit tests
        run: docker run -e MIX_ENV=test --name billet_manager --network billet_manager billet_manager:latest mix test --only unit --branch ${GITHUB_REF#refs/heads/} --name "GitHub Actions" --committer $GITHUB_ACTOR --message "${{ github.event.head_commit.message }}" --sha $GITHUB_SHA

  integration-tests:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.6.0
          with:
            access_token: ${{ github.token }}

        - name: Download artifact (image)
          uses: actions/download-artifact@v2
          with:
            name: app
            path: /tmp
        - name: Download artifact (compose)
          uses: actions/download-artifact@v2
          with:
            name: compose
            path: .
        - name: Load Docker image
          run: docker load --input /tmp/image.tar

        - name: Starting DB
          run: docker-compose up -d db

        - name: Load Docker image
          run: docker load --input /tmp/image.tar

        - name: Integration tests
          run: docker run -e MIX_ENV=test --name cobranca --network solfacil cobranca:latest mix coveralls.post --include integration --token ${{ secrets.COVERALLS_TOKEN }} --branch ${GITHUB_REF#refs/heads/} --name "GitHub Actions" --committer $GITHUB_ACTOR --message "${{ github.event.head_commit.message }}" --sha $GITHUB_SHA

  migrations-rollback:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.6.0
          with:
            access_token: ${{ github.token }}

        - name: Download artifact (image)
          uses: actions/download-artifact@v2
          with:
            name: app
            path: /tmp
        - name: Download artifact (compose)
          uses: actions/download-artifact@v2
          with:
            name: compose
            path: .
        - name: Load Docker image
          run: docker load --input /tmp/image.tar

        - name: Starting DB
          run: docker-compose up -d db

        - name: Load Docker image
          run: docker load --input /tmp/image.tar

        - name: Migrations rollback test
          run: |
            docker run --rm -e MIX_ENV=test --name cobranca --network solfacil cobranca:latest mix ecto.setup
            docker run --rm -e MIX_ENV=test --name cobranca --network solfacil cobranca:latest mix ecto.rollback --all
            docker run --rm -e MIX_ENV=test --name cobranca --network solfacil cobranca:latest mix ecto.migrate
